### ISSUE TITLE
Error creating tasks : AttributeError: 'RPCResponse' object has no attribute 'message'

### ISSUE THREAD

**Issue by Nicknam3** [its-a-feature/Mythic#197]
Hi the Team,

First of all, thanks for the good work ^^

I've some issue when using register_assembly or powershell_import:

```
[-] apollo ran into an error processing powershell_import: 
'RPCResponse' object has no attribute 'message'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mythic_payloadtype_container/mythic_service.py", line 277, in callback
    final_task = await Command.create_tasking(task)
  File "/Mythic/mythic/agent_functions/powershell_import.py", line 54, in create_tasking
    raise Exception("Failed to create subtask: {}".format(response.message))
AttributeError: 'RPCResponse' object has no attribute 'message'

```
```[-] apollo ran into an error processing register_assembly: 
'RPCResponse' object has no attribute 'message'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mythic_payloadtype_container/mythic_service.py", line 277, in callback
    final_task = await Command.create_tasking(task)
  File "/Mythic/mythic/agent_functions/register_assembly.py", line 54, in create_tasking
    raise Exception("Failed to create subtask: {}".format(response.message))
AttributeError: 'RPCResponse' object has no attribute 'message'
```

It's ok when i use some other commands : run, mkdir, ls, etc.

Any idea ?

Thanks,

Nicknam3

**Comment by its-a-feature** [comment]
I'd suggest opening this against the Apollo repository. When you do this and get this error, can you run `sudo ./mythic-cli logs mythic_server` and share that output here too?

**Comment by Nicknam3** [comment]
Thanks for the quick response. I will post it against the Apollo repository. For information here is my log:

```
...
[2022-03-22 21:50:57 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:51:07 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:51:16 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:51:25 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:51:37 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:51:48 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:52:00 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:52:07 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:52:19 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:52:31 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:52:39 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:52:51 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:53:02 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:53:02 +0000] [32] [INFO] CREATED TASK 64
[2022-03-22 21:53:02 +0000] [32] [INFO] SUBMITTING 64 TO CONTAINER
[2022-03-22 21:53:02 +0000] [32] [INFO] RABBITMQ GOT CREATE_TASK INFO BACK FROM CONTAINER FOR 64 WITH STATUS CODE success
[2022-03-22 21:53:02 +0000] [32] [INFO] RABBITMQ CALLED UPDATE ON TASK BACK FROM CONTAINER FOR 64 WITH STATUS submitted FROM CREATE_TASKING
[2022-03-22 21:53:14 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:53:25 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:53:25 +0000] [32] [INFO] {'status': 'success'}
[2022-03-22 21:53:25 +0000] [36] [INFO] Setting task 64 status to: completed with completion status: True
[2022-03-22 21:53:25 +0000] [36] [INFO] issuing task callback functions for task 64 with status: completed
[2022-03-22 21:53:34 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
[2022-03-22 21:53:46 +0000] [32] [INFO] len of redis list for SOCKS:5:ToAgent is 0
```

**Comment by Nicknam3** [comment]
See here : https://github.com/MythicAgents/Apollo/issues/93
