### ISSUE TITLE
v3.0.0 Jupyter install failure

### ISSUE THREAD

**Issue by scottctaylor12** [its-a-feature/Mythic#272]
When installing Mythic v3.0.0, the mythic_jupyter container failed to build and produced the error message below.
I had Mythic v2 running on the same machine before, so I figured I'd attempt to "wipe clean" and start from scratch. That process was:
- Stopping & Removing the containers
- Removing the container images
- Recursively removing my /opt/Mythic install directory
- git clone Mythic
- git checkout v3.0.0
- sudo make

Because jupyter is failing to build, the Mythic is not starting up. 

```
┌──(kali㉿kali)-[/opt/Mythic]
└─$ sudo ./mythic-cli start
[*] No build.env file detected in Mythic's root directory; not supplying build arguments to docker containers
    If you need to supply build arguments to docker containers, create build.env and supply key=value entries there
No stopped containers
[+] Successfully made ssl folder in nginx-docker folder
[*] Failed to find SSL certs for Nginx container, generating now...
[+] Successfully generated new SSL certs
Building mythic_documentation
Sending build context to Docker daemon  6.398MB
Step 1/2 : FROM klakegg/hugo:latest
 ---> 0fa41585b848
Step 2/2 : RUN hugo new site mythic_docs
 ---> Using cache
 ---> 3a88126fbdc1
Successfully built 3a88126fbdc1
Successfully tagged mythic_documentation:latest
Building mythic_graphql
Sending build context to Docker daemon  426.5kB
Step 1/1 : FROM hasura/graphql-engine:latest.cli-migrations-v2
 ---> 3a6c595b3a29
Successfully built 3a6c595b3a29
Successfully tagged mythic_graphql:latest
Building mythic_jupyter
Sending build context to Docker daemon  97.79kB
Step 1/5 : FROM jupyter/base-notebook:python-3.10
 ---> 91d725edce1e
Step 2/5 : RUN pip3 uninstall -y mythic
 ---> Using cache
 ---> e4084c6197a4
Step 3/5 : RUN pip3 install mythic==0.1.0rc2
 ---> Running in 6ce216767416
Collecting mythic==0.1.0rc2
  Downloading mythic-0.1.0rc2-py3-none-any.whl (35 kB)
Collecting asyncio
  Downloading asyncio-3.4.3-py3-none-any.whl (101 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 52, in _rich_progress_bar
    with progress:
  File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/rich/progress.py", line 1169, in __enter__
    self.start()
  File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/rich/progress.py", line 1160, in start
    self.live.start(refresh=True)
  File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/rich/live.py", line 132, in start
    self._refresh_thread.start()
  File "/opt/conda/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
The command '/bin/bash -o pipefail -c pip3 install mythic==0.1.0rc2' returned a non-zero code: 2
Service 'mythic_jupyter' failed to build : Build failed

[-] Error from docker-compose: exit status 1
```

**Comment by its-a-feature** [comment]
I saw this before - what's your current docker and docker compose versions?

**Comment by its-a-feature** [comment]
https://docs.mythic-c2.net/v/version-3.0/installation#get-the-code i made a note of it here in the installation, but I should add a check as part of mythic-cli too

**Comment by scottctaylor12** [comment]
Ahh that would be it.. I have an outdated version of docker. Thanks for the help!
┌──(kali㉿kali)-[/opt/poseidon]
└─$ docker --version       
Docker version 20.10.3+dfsg1, build 48d30b5
                                                                                                                                                                                                                   
┌──(kali㉿kali)-[/opt/poseidon]
└─$ docker-compose --version
docker-compose version 1.29.2, build unknown

**Comment by its-a-feature** [comment]
Just pushed a check in mythic-cli to make sure the docker version is high enough
